### ISSUE TITLE
can you provide the txt file used for read_detection?

### ISSUE THREAD

**Issue by Egolee0713** [yeyang1021/KITTI_VIZ_3D#1]
hi, can you provide the txt file used for read_detection?

**Comment by yeyang1021** [comment]
I can provide an example for you!

KITTI test dataset   
The detected results for 003500.txt: 
Car 0.0000 0.0000 -0.9113 0.0000 194.6118 291.6947 361.0103 1.4407 1.5384 3.4081 -5.3338 1.6414 8.1906 -1.4694 0.8523
Car 0.0000 0.0000 -1.5562 559.6336 173.1650 582.1243 194.7984 1.6289 1.6924 3.7365 -2.6193 1.0779 55.1278 -1.6018 0.4969

**Comment by yeyang1021** [comment]
> hi, can you provide the txt file used for read_detection?

I can provide an example for you!

KITTI test dataset
The detected results for 003500.txt:
Car 0.0000 0.0000 -0.9113 0.0000 194.6118 291.6947 361.0103 1.4407 1.5384 3.4081 -5.3338 1.6414 8.1906 -1.4694 0.8523
Car 0.0000 0.0000 -1.5562 559.6336 173.1650 582.1243 194.7984 1.6289 1.6924 3.7365 -2.6193 1.0779 55.1278 -1.6018 0.4969
