### ISSUE TITLE
Couldn't find draw picture code in draw_box_lidar.py

### ISSUE THREAD

**Issue by hyzhou404** [yeyang1021/KITTI_VIZ_3D#2]
I found you import matplotlib, but not used. Points are just saved to a txt file, how to visualize these points?

**Comment by yeyang1021** [comment]
> I found you import matplotlib, but not used. Points are just saved to a txt file, how to visualize these points?

You need to download the meshlab software for visualization. Please use meshlab to read the data in the txt file for visualization.
