### ISSUE TITLE
MeshLab visualization problem

### ISSUE THREAD

**Issue by Goldcamel** [yeyang1021/KITTI_VIZ_3D#4]
Hi Yeyang,

Could you please tell the format of the txt file? It's a n x 7 matrix and what every column represents? I imported the txt file to MeshLab but points can't be read and displayed.

Thanks

**Comment by yeyang1021** [comment]
> Hi Yeyang,
> 
> Could you please tell the format of the txt file? It's a n x 7 matrix and what every column represents? I imported the txt file to MeshLab but points can't be read and displayed.
> 
> Thanks


The seven values are x, y, z, i, r, g, b. 
x,y,z are coordinates in the point cloud.
i means reflectance information.
r,g,b are RGB values drawn on the image.

Notice:
You need to set the format of the data to use meshlab normally.
