### ISSUE TITLE
MeshLab visualization problem

### ISSUE THREAD

**Issue by freshwk** [yeyang1021/KITTI_VIZ_3D#5]
![QQ图片20210715104055](https://user-images.githubusercontent.com/42930372/125719493-f5c7bb34-fccb-48b5-92a9-76cab7a3a8cb.jpg)
I imported the txt file to MeshLab but points can't be   displayed.But it seems that the points have been readed.Could you please tell me why？

**Comment by yeyang1021** [comment]
I will provide a document for reference.

**Comment by yeyang1021** [comment]
> ![QQ图片20210715104055](https://user-images.githubusercontent.com/42930372/125719493-f5c7bb34-fccb-48b5-92a9-76cab7a3a8cb.jpg)
> I imported the txt file to MeshLab but points can't be displayed.But it seems that the points have been readed.Could you please tell me why？

I will provide a document for reference.
